apiVersion: v1
kind: Service
metadata:
  name: face-recognizer-api-svc
  labels:
    app: face-recognizer-api-svc
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: face-recognizer-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognizer-api
spec:
  selector:
    matchLabels:
      app: face-recognizer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: face-recognizer-api
    spec:
      containers:
      - name: face-recognizer-api
        image: 192.168.1.5:5000/face_recognizer-api:1.0.0
        #command: ["sleep"]
        #args: ["360000"]
        ports:
        - containerPort: 5000
        resources:
          limits:
             nvidia.com/gpu: 1
        securityContext:
          privileged: true
        volumeMounts:
        - name: face-recognizer-csi-data
          mountPath: /mnt
      volumes:
        - name: face-recognizer-csi-data
          persistentVolumeClaim:
            claimName: pvc-nfs-vm-dynamic
